### ISSUE TITLE
No Labels

### ISSUE THREAD

**Issue by NickJT52** [SalekurPolas/MMM-Pinfo#1]
Hi,

I've installed MMM-Pinfo and while it's showing the stats, I can't find a way to display the labels.

Is there a setting somewhere I need to enable them?

Regards
![Pinfo](https://user-images.githubusercontent.com/102603101/160627345-7c9d0dd9-9a8f-43c9-aca7-9a4779d23bc0.jpg)

**Comment by SalekurPolas** [comment]
@NickJT52, Can you please mention the Raspberry Pi and Node.js versions?
Try to configure items and levels alignment, and don't forget to set size if your RPI with Electron is not up to date.

`{
    module: 'MMM-Pinfo',
    position: 'top_left',
    config: {
      itemAlign: 'left',
      labelAlign: 'left',
      valueAlign: 'center',
      labelSize: null,
      containerSize: null
    }
  }`

**Comment by Kayakbabe** [comment]
is containerSize the RPI size? for example if I have a 4MB RPI4, then do I set containersize to 4? 
Also what is the variable for the SD card size?
